# Default configuration for MediaMTX Camera Service
# This file contains all configurable parameters with their default values

server:
  host: "0.0.0.0"
  port: 8002
  websocket_path: "/ws"
  max_connections: 1000
  read_timeout: 5s
  write_timeout: 1s
  ping_interval: 30s
  pong_wait: 60s
  max_message_size: 1048576  # 1MB

mediamtx:
  host: "localhost"
  api_port: 9997
  rtsp_port: 8554
  webrtc_port: 8889
  hls_port: 8888
  config_path: "/etc/mediamtx/mediamtx.yml"
  recordings_path: "/opt/camera-service/recordings"
  snapshots_path: "/opt/camera-service/snapshots"
  health_check_interval: 30
  health_failure_threshold: 3
  health_circuit_breaker_timeout: 60
  health_max_backoff_interval: 300
  health_recovery_confirmation_threshold: 2
  backoff_base_multiplier: 2.0
  backoff_jitter_range: [0.1, 0.3]
  process_termination_timeout: 10.0
  process_kill_timeout: 5.0
  health_check_timeout: 5s
  codec:
    video_profile: "baseline"
    video_level: "3.1"
    pixel_format: "yuv420p"
    bitrate: "2M"
    preset: "fast"
  stream_readiness:
    timeout: 30.0
    retry_attempts: 3
    retry_delay: 1.0
    check_interval: 1.0
    enable_progress_notifications: true
    graceful_fallback: true

camera:
  poll_interval: 5.0
  detection_timeout: 10.0
  device_range: [0, 9]
  enable_capability_detection: true
  auto_start_streams: false
  capability_timeout: 5.0
  capability_retry_interval: 1.0
  capability_max_retries: 3

logging:
  level: "info"
  format: "json"
  file_enabled: true
  file_path: "/var/log/camera-service.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5
  console_enabled: true

recording:
  enabled: true
  format: "mp4"
  quality: "medium"
  segment_duration: 300  # 5 minutes
  max_segment_size: 104857600  # 100MB
  auto_cleanup: true
  cleanup_interval: 3600  # 1 hour
  max_age: 604800  # 7 days
  max_size: 1073741824  # 1GB
  default_rotation_size: 104857600  # 100MB
  default_max_duration: 24h
  default_retention_days: 7

snapshots:
  enabled: true
  format: "jpeg"
  quality: 85
  max_width: 1920
  max_height: 1080
  auto_cleanup: true
  cleanup_interval: 3600  # 1 hour
  max_age: 604800  # 7 days
  max_count: 1000

ffmpeg:
  snapshot:
    process_creation_timeout: 10.0
    execution_timeout: 30.0
    internal_timeout: 5
    retry_attempts: 3
    retry_delay: 1.0
  recording:
    process_creation_timeout: 10.0
    execution_timeout: 30.0
    internal_timeout: 5
    retry_attempts: 3
    retry_delay: 1.0

notifications:
  websocket:
    delivery_timeout: 5.0
    retry_attempts: 3
    retry_delay: 1.0
    max_queue_size: 1000
    cleanup_interval: 300  # 5 minutes
  real_time:
    camera_status_interval: 30.0
    recording_progress_interval: 10.0
    connection_health_check: 60.0

performance:
  response_time_targets:
    snapshot_capture: 2.0
    recording_start: 5.0
    recording_stop: 3.0
    file_listing: 1.0
  snapshot_tiers:
    tier1_usb_direct_timeout: 1.0
    tier2_rtsp_ready_check_timeout: 2.0
    tier3_activation_timeout: 5.0
    tier3_activation_trigger_timeout: 10.0
    total_operation_timeout: 15.0
    immediate_response_threshold: 0.5
    acceptable_response_threshold: 2.0
    slow_response_threshold: 5.0
  optimization:
    enable_caching: true
    cache_ttl: 300  # 5 minutes
    max_concurrent_operations: 10
    connection_pool_size: 5

# Security configuration (Phase 1 enhancement)
security:
  rate_limit_requests: 100  # Requests per window
  rate_limit_window: 1m     # Time window for rate limiting
  jwt_secret_key: "your-secret-key-here"  # Must be set in production
  jwt_expiry_hours: 24      # JWT token expiry in hours

# Storage configuration (Phase 2 enhancement)
storage:
  warn_percent: 80    # Storage usage warning threshold
  block_percent: 90   # Storage usage block threshold
  default_path: "/opt/camera-service/recordings"
  fallback_path: "/tmp/recordings"

# Optional health server port for testing
health_port: 8080
