# MediaMTX Camera Service - Development Configuration

server:
  host: "0.0.0.0"
  port: 8080
  websocket_path: "/ws"
  max_connections: 100

mediamtx:
  host: "127.0.0.1"
  api_port: 9997
  rtsp_port: 8554
  webrtc_port: 8889
  hls_port: 8888
  config_path: "./config/mediamtx.yml"
  recordings_path: "./recordings"
  snapshots_path: "./snapshots"
  
  # Health monitoring configuration
  health_check_interval: 30
  health_failure_threshold: 10
  health_circuit_breaker_timeout: 60
  health_max_backoff_interval: 120
  health_recovery_confirmation_threshold: 3
  backoff_base_multiplier: 2.0
  backoff_jitter_range: [0.8, 1.2]
  process_termination_timeout: 3.0
  process_kill_timeout: 2.0

camera:
  poll_interval: 0.05  # Reduced from 0.1s to 0.05s (50ms) for faster detection
  detection_timeout: 2.0
  device_range: [0, 9]  # /dev/video0 to /dev/video9
  enable_capability_detection: true
  auto_start_streams: true
  capability_timeout: 5.0
  capability_retry_interval: 1.0
  capability_max_retries: 3

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: false  # Disable file logging for development
  file_path: "./logs/camera-service.log"
  max_file_size: 10485760
  backup_count: 5
  console_enabled: true

recording:
  enabled: false
  format: "fmp4"
  quality: "high"
  segment_duration: 3600
  max_segment_size: 524288000
  auto_cleanup: true
  cleanup_interval: 86400
  max_age: 604800
  max_size: 10737418240

snapshots:
  enabled: true
  format: "jpeg"
  quality: 90
  max_width: 1920
  max_height: 1080
  auto_cleanup: true
  cleanup_interval: 3600
  max_age: 86400
  max_count: 1000
