# Development Configuration
mediamtx:
  recordings_path: "/tmp/dev/recordings"  # Local temp storage
  snapshots_path: "/tmp/dev/snapshots"
  override_mediamtx_paths: true

storage:
  default_path: "/tmp/dev/recordings"
  fallback_path: "/tmp/fallback"  # Fallback to different temp location
  
  # Relaxed limits for development
  warn_percent: 90
  block_percent: 99