version: '3.8'

services:
  silvus-mock:
    build: .
    container_name: silvus-mock
    networks:
      radionet:
        ipv4_address: 172.20.1.10
    environment:
      - CBTIMING_CONFIG=/etc/cb-timing.yaml
      - SILVUS_MOCK_MODE=normal
    volumes:
      - ./config/cb-timing.example.yaml:/etc/cb-timing.yaml:ro
    ports:
      - "8080:80"
      - "50000:50000"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/streamscape_api"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Example RCC service (replace with your actual RCC image)
  rcc:
    image: your-rcc:latest
    container_name: rcc-test
    networks:
      radionet:
        ipv4_address: 172.20.0.1
    depends_on:
      silvus-mock:
        condition: service_healthy
    environment:
      - RADIO_SILVUS_ADDR=172.20.1.10
      - RADIO_SILVUS_PORT=80
    ports:
      - "8002:8002"  # RCC command API
      - "8003:8003"  # RCC telemetry SSE

networks:
  radionet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
