# MediaMTX Camera Service - Anti-Hardcoding Linter Configuration
# Prevents hardcoded values that violate architectural principles

version: 2

run:
  timeout: 5m
  tests: true

linters-settings:
  # CRITICAL: Detect hardcoded constants
  goconst:
    min-len: 2
    min-occurrences: 2
    numbers: true  # Catches numeric constants like -32503, 8002, 404
    ignore-tests: false  # Tests must also avoid hardcoding
    
  # CRITICAL: Detect magic numbers  
  mnd:
    ignored-numbers:
      - "0"
      - "1" 
      - "2"
      - "10"
      - "100"
      - "1000"
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign

linters:
  enable:
    - goconst  # Hardcoded constants detection
    - mnd      # Magic numbers detection
    - govet    # Go vet analysis
    
issues:
  max-issues-per-linter: 0
  max-same-issues: 0