linters:
  enable:
    - errcheck
    - staticcheck
    - gocritic
    - stylecheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  staticcheck:
    go: "1.21"
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  stylecheck:
    go: "1.21"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false