# Radio Control Container Configuration Example
# Source: CB-TIMING v0.3 - Single source of truth for all timing parameters

system:
  service_name: "radio-control-container"
  version: "1.0.0"
  listen_address: "0.0.0.0"
  port: 8002
  auth_required: true

timing:
  telemetry:
    heartbeat_interval: "15s"
    heartbeat_jitter: "2s"
    heartbeat_timeout: "45s"
    state_update_hz: 1
    burst_protection_hz: 10
  
  health:
    normal:
      initial_interval: "30s"
      backoff_factor: 1.0
      max_interval: "30s"
      jitter_window: "5s"
    recovering:
      initial_interval: "5s"
      backoff_factor: 1.5
      max_interval: "15s"
      jitter_window: "2s"
    offline:
      initial_interval: "10s"
      backoff_factor: 2.0
      max_interval: "300s"
      jitter_window: "10s"
    max_probes_per_hour: 100
    probe_timeout: "5s"
    concurrent_probe_limit: 3
  
  commands:
    set_power:
      timeout: "10s"
      retry_count: 3
      backoff_base: "1s"
    set_channel:
      timeout: "30s"
      retry_count: 2
      backoff_base: "2s"
    select_radio:
      timeout: "5s"
      retry_count: 3
      backoff_base: "500ms"
    get_state:
      timeout: "5s"
      retry_count: 2
      backoff_base: "1s"
  
  events:
    buffer_size_per_radio: 50
    buffer_retention: "1h"
    channel_change_blackout: "30s"
    power_change_blackout: "5s"
    radio_reset_blackout: "60s"
  
  backoff:
    base_delay: "500ms"
    jitter_range: "250ms"
    max_retries: 5
    exponential_factor: 2.0
    max_delay: "30s"
    error_policies:
      BUSY:
        initial_delay: "1s"
        max_retries: 3
        backoff_factor: 1.5
      UNAVAILABLE:
        initial_delay: "2s"
        max_retries: 5
        backoff_factor: 2.0
      INTERNAL:
        initial_delay: "500ms"
        max_retries: 3
        backoff_factor: 2.0
  
  power:
    cpu_idle_target: 5.0
    cpu_burst_limit: 20.0
    probe_budget: 100
    event_first_policy: true
    max_duty_cycle: 0.1
    min_sleep_interval: "100ms"

channels:
  frequency_tolerance: 0.1  # ±0.1 MHz
  index_base: 1  # 1-based per ADR-002
  frequency_precedence: true
  radio_channels:
    silvus-01:
      radio_id: "silvus-01"
      model: "Silvus-XXXX"
      channels:
        - index: 1
          frequency_mhz: 2412.0
          description: "Channel 1"
        - index: 2
          frequency_mhz: 2417.0
          description: "Channel 2"
        - index: 3
          frequency_mhz: 2422.0
          description: "Channel 3"
      last_update: "2025-01-15T10:00:00Z"

power:
  default_min_power_dbm: 0
  default_max_power_dbm: 39
  radio_power_limits:
    silvus-01:
      min_power_dbm: 0
      max_power_dbm: 39

logging:
  log_max_file_mb: 10
  log_keep_files: 5
  log_rotation_trigger: "size-based"
  audit_log_retention_days: 30
  telemetry_buffer_hours: "1h"
