# Camera Service Configuration
server:
  host: "0.0.0.0"
  port: 8002
  websocket_path: "/ws"
  max_connections: 100

security:
  jwt:
    secret_key: "${JWT_SECRET_KEY}"
    expiry_hours: 24
    algorithm: "HS256"
  
  api_keys:
    storage_file: "${API_KEYS_FILE}"
  
  ssl:
    enabled: false
    cert_file: "${SSL_CERT_FILE}"
    key_file: "${SSL_KEY_FILE}"
  
  rate_limiting:
    max_connections: 100
    requests_per_minute: 60
  
  health:
    port: 8003
    bind_address: "0.0.0.0"

mediamtx:
  host: "localhost"
  api_port: 9997
  rtsp_port: 8554
  webrtc_port: 8889
  hls_port: 8888
  config_path: "/etc/mediamtx/mediamtx.yml"
  recordings_path: "/var/recordings"
  snapshots_path: "/var/snapshots"

cameras:
  discovery_enabled: true
  polling_interval: 30

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true
  file_path: "/var/log/camera-service/camera-service.log"
  max_file_size: "10MB"
  backup_count: 5

recording:
  auto_record: false
  format: "mp4"
  quality: "medium"
  max_duration: 3600
  cleanup_after_days: 30

snapshots:
  format: "jpg"
  quality: 85
  cleanup_after_days: 7 