# MediaMTX Camera Service - Default Configuration

server:
  host: "0.0.0.0"
  port: 8002
  websocket_path: "/ws"
  max_connections: 100

mediamtx:
  host: "127.0.0.1"
  api_port: 9997
  rtsp_port: 8554
  webrtc_port: 8889
  hls_port: 8888
  config_path: "/opt/camera-service/config/mediamtx.yml"
  recordings_path: "/opt/camera-service/recordings"
  snapshots_path: "/opt/camera-service/snapshots"
  
  # Codec configuration for STANAG 4406 compatibility
  codec:
    video_profile: "baseline"  # baseline, main, high
    video_level: "3.0"         # 1.0, 1.1, 1.2, 1.3, 2.0, 2.1, 2.2, 3.0, 3.1, 3.2, 4.0, 4.1, 4.2, 5.0, 5.1, 5.2
    pixel_format: "yuv420p"    # yuv420p, yuv422p, yuv444p
    bitrate: "600k"            # Video bitrate
    preset: "ultrafast"        # ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow
  
  # Health monitoring configuration
  health_check_interval: 30        # Normal health check interval (seconds)
  health_failure_threshold: 10     # Failures before circuit breaker activates
  health_circuit_breaker_timeout: 60   # Circuit breaker timeout (seconds)
  health_max_backoff_interval: 120     # Maximum backoff interval (seconds)
  health_recovery_confirmation_threshold: 3  # Consecutive successes to reset circuit breaker
  backoff_base_multiplier: 2.0     # Base multiplier for exponential backoff
  backoff_jitter_range: [0.8, 1.2] # Jitter range for backoff randomization (will be converted to tuple)
  process_termination_timeout: 3.0  # Timeout for graceful process termination
  process_kill_timeout: 2.0        # Timeout for force kill after termination
  
  # Stream readiness configuration for improved reliability
  stream_readiness:
    timeout: 15.0                   # Increased from 5.0s to 15.0s for reliability
    retry_attempts: 3               # Number of retry attempts
    retry_delay: 2.0                # Delay between retries in seconds
    check_interval: 0.5             # Interval between readiness checks
    enable_progress_notifications: true  # Send progress notifications during validation
    graceful_fallback: true         # Enable graceful fallback when streams unavailable

# FFmpeg configuration for performance tuning
ffmpeg:
  snapshot:
    process_creation_timeout: 5.0    # seconds
    execution_timeout: 8.0           # seconds
    internal_timeout: 5000000        # microseconds
    retry_attempts: 2
    retry_delay: 1.0                 # seconds
  
  recording:
    process_creation_timeout: 10.0   # seconds
    execution_timeout: 15.0          # seconds
    internal_timeout: 10000000       # microseconds
    retry_attempts: 3
    retry_delay: 2.0                 # seconds

# Notification configuration for real-time updates
notifications:
  websocket:
    delivery_timeout: 5.0            # seconds
    retry_attempts: 3
    retry_delay: 1.0                 # seconds
    max_queue_size: 1000
    cleanup_interval: 30             # seconds
  
  real_time:
    camera_status_interval: 1.0      # seconds
    recording_progress_interval: 0.5 # seconds
    connection_health_check: 10.0    # seconds

# Performance tuning configuration
performance:
  response_time_targets:
    snapshot_capture: 2.0            # seconds
    recording_start: 2.0             # seconds
    recording_stop: 2.0              # seconds
    file_listing: 1.0                # seconds
  
  optimization:
    enable_caching: true
    cache_ttl: 300                   # seconds
    max_concurrent_operations: 5
    connection_pool_size: 10

camera:
  poll_interval: 0.1
  detection_timeout: 2.0
  device_range: [0, 9]  # /dev/video0 to /dev/video9
  enable_capability_detection: true
  auto_start_streams: true
  capability_timeout: 5.0
  capability_retry_interval: 1.0
  capability_max_retries: 3

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true
  file_path: "/opt/camera-service/logs/camera-service.log"
  max_file_size: 10485760
  backup_count: 5
  console_enabled: true

recording:
  enabled: false
  format: "fmp4"
  quality: "high"
  segment_duration: 3600  # 1 hour
  max_segment_size: 524288000
  auto_cleanup: true
  cleanup_interval: 86400
  max_age: 604800
  max_size: 10737418240

snapshots:
  enabled: true
  format: "jpeg"
  quality: 90
  max_width: 1920
  max_height: 1080
  auto_cleanup: true
  cleanup_interval: 3600
  max_age: 86400
  max_count: 1000
