# MediaMTX Camera Service - Production Configuration
# Based on existing default.yaml and camera-service-fixed.yaml

server:
  host: "0.0.0.0"
  port: 8002
  websocket_path: "/ws"
  max_connections: 100

# Use existing SSL configuration structure from src/common/config.py
security:
  jwt:
    secret_key: "${CAMERA_SERVICE_JWT_SECRET}"
    expiry_hours: 24
    algorithm: "HS256"
  
  api_keys:
    storage_file: "${API_KEYS_FILE}"
  
  ssl:
    enabled: true  # Production: HTTPS enabled
    cert_file: "/opt/camera-service/ssl/cert.pem"
    key_file: "/opt/camera-service/ssl/key.pem"
  
  rate_limiting:
    max_connections: 100
    requests_per_minute: 60
  
  health:
    port: 8003
    bind_address: "0.0.0.0"

mediamtx:
  host: "localhost"
  api_port: 9997
  rtsp_port: 8554
  webrtc_port: 8889
  hls_port: 8888
  config_path: "/opt/camera-service/config/mediamtx.yml"
  recordings_path: "/opt/camera-service/recordings"
  snapshots_path: "/opt/camera-service/snapshots"
  
  # Use existing health monitoring configuration
  health_check_interval: 30
  health_failure_threshold: 10
  health_circuit_breaker_timeout: 60
  health_max_backoff_interval: 120
  health_recovery_confirmation_threshold: 3
  backoff_base_multiplier: 2.0
  backoff_jitter_range: [0.8, 1.2]
  process_termination_timeout: 3.0
  process_kill_timeout: 2.0

camera:
  poll_interval: 0.1
  detection_timeout: 2.0
  device_range: [0, 9]
  enable_capability_detection: true
  auto_start_streams: true
  capability_timeout: 5.0
  capability_retry_interval: 1.0
  capability_max_retries: 3

# Use existing logging configuration with production settings
logging:
  level: "WARNING"  # Production: Reduced logging
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true
  file_path: "/opt/camera-service/logs/camera-service.log"
  max_file_size: 10485760
  backup_count: 5  # Use existing backup configuration
  console_enabled: false  # Production: Console logging disabled

recording:
  enabled: false
  format: "fmp4"
  quality: "high"
  segment_duration: 3600
  max_segment_size: 524288000
  auto_cleanup: true
  cleanup_interval: 86400
  max_age: 604800
  max_size: 10737418240

snapshots:
  enabled: true
  format: "jpeg"
  quality: 90
  max_width: 1920
  max_height: 1080
  auto_cleanup: true
  cleanup_interval: 3600
  max_age: 86400
  max_count: 1000
