# CB-TIMING v0.3 Configuration Example
# This file can be mounted and referenced via CBTIMING_CONFIG environment variable

# Heartbeat configuration (CB-TIMING ยง3)
heartbeat:
  intervalSec: 15
  jitterSec: 2
  timeoutSec: 45

# Probe cadences (CB-TIMING ยง4)
probes:
  normal:
    intervalSec: 30
  recovering:
    intervalMinSec: 5
    intervalMaxSec: 15
  offline:
    intervalMinSec: 10
    intervalMaxSec: 300

# Command timeouts (CB-TIMING ยง5)
timing:
  blackout:
    softBootSec: 5  # Override default soft boot duration
  commands:
    setPower:
      timeoutSec: 10
    setChannel:
      timeoutSec: 30
    selectRadio:
      timeoutSec: 5
    getState:
      timeoutSec: 5
  backoff:
    busyBaseMs: 1000
    exponentialMaxMs: 10000

# Event buffering (CB-TIMING ยง6)
buffering:
  maxEvents: 50
  retentionHours: 1
  resumeStrategy: "last-event-id"
