# Silvus Radio Mock Configuration
# Based on ICD and CB-TIMING specifications

network:
  http:
    port: 8080
    serverHeader: ""  # Suppress server identification
  maintenance:
    port: 50000
    allowedCidrs:
      - "127.0.0.0/8"      # Localhost
      - "172.20.0.0/16"    # Radio network

# Frequency profiles from ICD §6.1.2
profiles:
  frequencyProfiles:
    - frequencies:
        - "2200:20:2380"   # Range format: start:step:end
        - "4700"           # Single frequency
      bandwidth: "-1"      # All supported bandwidths (5 and 20 MHz)
      antenna_mask: "15"   # Hex bitmask for RX channels
    - frequencies:
        - "4420:40:4700"
      bandwidth: "-1"
      antenna_mask: "3"
    - frequencies:
        - "4700:20:4980"
      bandwidth: "-1"
      antenna_mask: "12"

# Power limits per ICD §6.1.3
power:
  minDbm: 0
  maxDbm: 39

# Timing configuration based on CB-TIMING v0.3
timing:
  blackout:
    softBootSec: 5  # Will be overridden by CBTIMING_CONFIG if present
  commands:
    setPower:
      timeoutSec: 10  # CB-TIMING §5
    setChannel:
      timeoutSec: 30  # CB-TIMING §5
    selectRadio:
      timeoutSec: 5   # CB-TIMING §5
    read:
      timeoutSec: 5   # CB-TIMING §5
  backoff:
    busyBaseMs: 1000

# Operation mode
mode: "normal"  # normal, degraded, offline
